/**
 * The three build outputs.
 *
 *  - `icons.svg`        — one `<symbol id="mv-<key>">` per icon, consumed with
 *                         `<use href="/icons/icons.svg#mv-stat-atk" />`
 *  - `icons.json`       — machine-readable manifest for the client and the Credits screen
 *  - `ATTRIBUTION.md`   — the CC BY 3.0 credit, grouped by author, for CREDITS.md and
 *                         Settings → Credits
 *
 * The licence notice is embedded in the sprite itself, so the obligation travels with the file
 * even if someone copies it out of the repo.
 */

import type { IconGroup, IconKey } from './icons.js';
import { ICON_GROUP_LABELS } from './icons.js';
import {
  AUTHORS_URL,
  LICENSE,
  LICENSE_URL,
  REPO_REF,
  REPO_URL,
  SITE_URL,
  authorDisplayName,
  pageUrlFor,
} from './source.js';

export interface IconEntry {
  readonly key: IconKey;
  readonly symbolId: string;
  readonly group: IconGroup;
  readonly use: string;
  readonly sourceName: string;
  readonly author: string;
  readonly viewBox: string;
  readonly body: string;
  readonly sourceUrl: string;
}

export const SPRITE_FILENAME = 'icons.svg';
export const MANIFEST_FILENAME = 'icons.json';
export const ATTRIBUTION_FILENAME = 'ATTRIBUTION.md';

const GENERATED_BY = 'tools/icon-fetch';

/** Builds the SVG sprite. `fill="currentColor"` on each symbol is what makes CSS tinting work. */
export function buildSprite(entries: readonly IconEntry[]): string {
  const lines: string[] = [
    '<svg xmlns="http://www.w3.org/2000/svg" width="0" height="0" style="position:absolute" aria-hidden="true" focusable="false">',
    `<!-- Generated by ${GENERATED_BY} — do not edit by hand.`,
    `     Icons from ${SITE_URL} (${REPO_URL}) by their respective authors,`,
    `     used under ${LICENSE}: ${LICENSE_URL}`,
    `     Per-icon authors: see ${ATTRIBUTION_FILENAME} / ${MANIFEST_FILENAME}. -->`,
  ];

  for (const entry of entries) {
    lines.push(
      `<symbol id="${entry.symbolId}" viewBox="${entry.viewBox}" fill="currentColor">${entry.body}</symbol>`,
    );
  }

  lines.push('</svg>', '');
  return lines.join('\n');
}

/** Builds the JSON manifest: metadata plus `key -> icon record`. */
export function buildManifest(entries: readonly IconEntry[], generatedAt: string): string {
  const icons: Record<string, unknown> = {};
  for (const entry of entries) {
    icons[entry.key] = {
      symbolId: entry.symbolId,
      sourceName: entry.sourceName,
      author: entry.author,
      authorName: authorDisplayName(entry.author),
      license: LICENSE,
      licenseUrl: LICENSE_URL,
      url: pageUrlFor(entry.author, entry.sourceName),
      sourceUrl: entry.sourceUrl,
      group: entry.group,
      use: entry.use,
    };
  }

  const manifest = {
    generatedBy: GENERATED_BY,
    generatedAt,
    sprite: SPRITE_FILENAME,
    source: { site: SITE_URL, repository: REPO_URL, ref: REPO_REF },
    license: LICENSE,
    licenseUrl: LICENSE_URL,
    count: entries.length,
    icons,
  };

  return `${JSON.stringify(manifest, null, 2)}\n`;
}

/** Builds the attribution document, grouped by author as the licence expects. */
export function buildAttribution(entries: readonly IconEntry[], generatedAt: string): string {
  const byAuthor = new Map<string, IconEntry[]>();
  for (const entry of entries) {
    const bucket = byAuthor.get(entry.author);
    if (bucket === undefined) byAuthor.set(entry.author, [entry]);
    else bucket.push(entry);
  }

  const authors = [...byAuthor.entries()].sort(([a], [b]) =>
    authorDisplayName(a).localeCompare(authorDisplayName(b)),
  );

  const out: string[] = [
    '# Icon attribution',
    '',
    `<!-- Generated by ${GENERATED_BY} on ${generatedAt} — do not edit by hand. -->`,
    '',
    `Mistvale's interface icons come from [game-icons.net](${SITE_URL}) (mirror: [\`game-icons/icons\`](${REPO_URL})).`,
    `They are used under the [Creative Commons Attribution 3.0 Unported licence (${LICENSE})](${LICENSE_URL}),`,
    'which requires that each author is credited wherever their work appears. The icons were',
    'recoloured and repacked into a sprite sheet for use in the game; the artwork itself is unchanged.',
    '',
    `**${String(entries.length)} icons by ${String(authors.length)} authors.**`,
    'Author profiles are listed on the',
    `[game-icons.net credits page](${AUTHORS_URL}).`,
    '',
  ];

  for (const [author, authorEntries] of authors) {
    const sorted = [...authorEntries].sort((a, b) => a.key.localeCompare(b.key));
    out.push(
      `## ${authorDisplayName(author)} — ${String(sorted.length)} ${sorted.length === 1 ? 'icon' : 'icons'}`,
      '',
      '| Mistvale key | Used for | Original icon |',
      '|---|---|---|',
    );
    for (const entry of sorted) {
      const group = ICON_GROUP_LABELS[entry.group];
      out.push(
        `| \`${entry.key}\` | ${group} — ${escapeCell(entry.use)} | [${entry.sourceName}](${pageUrlFor(entry.author, entry.sourceName)}) |`,
      );
    }
    out.push('');
  }

  out.push(
    '---',
    '',
    `Regenerate with \`pnpm --filter @mistvale/icon-fetch icons\`. The icon set is declared in`,
    '`tools/icon-fetch/src/icons.ts`.',
    '',
  );

  return out.join('\n');
}

function escapeCell(text: string): string {
  return text.replace(/\|/g, '\\|');
}
